### ISSUE TITLE
text templates failing on azure

### ISSUE THREAD

**Issue by tobiasnteireho** [CCALI/A2JDAT#65]
text templates are not rendering and yielding the following error on one azure box

```
3|CALI A2JDAT  | can-view-scope::attr is deprecated, please use peek, get or set
3|CALI A2JDAT  | Failed promise: TypeError: Cannot read property 'TEXT_NODE' of undefined
3|CALI A2JDAT  |     at Object.live.text (file:C:/inetpub/wwwroot/a2jdat-20201118/a2jdat/node_modules/can-view-live/lib/text.js:19:27)
3|CALI A2JDAT  |     at Text.branchRenderer (file:C:/inetpub/wwwroot/a2jdat-20201118/a2jdat/node_modules/can-stache/src/mustache_core.js:406:11)
3|CALI A2JDAT  |     at Comment.callback (file:C:/inetpub/wwwroot/a2jdat-20201118/a2jdat/node_modules/can-view-target/can-view-target.js:223:18)
3|CALI A2JDAT  |     at hydrateCallbacks (file:C:/inetpub/wwwroot/a2jdat-20201118/a2jdat/node_modules/can-view-target/can-view-target.js:262:39)
3|CALI A2JDAT  |     at Object.hydrate (file:C:/inetpub/wwwroot/a2jdat-20201118/a2jdat/node_modules/can-view-target/can-view-target.js:284:4)
3|CALI A2JDAT  |     at HelperOptions.convertedRenderer (file:C:/inetpub/wwwroot/a2jdat-20201118/a2jdat/node_modules/can-stache/src/utils.js:80:17)
3|CALI A2JDAT  |     at HelperOptions.fn (file:C:/inetpub/wwwroot/a2jdat-20201118/a2jdat/node_modules/can-observation-recorder/can-observation-recorder.js:87:18)
3|CALI A2JDAT  |     at A2JVariableVM.ifHelper (file:C:/inetpub/wwwroot/a2jdat-20201118/a2jdat/node_modules/can-stache/helpers/core.js:215:26)
3|CALI A2JDAT  |     at {{if(canShowAnswer)}} (file:C:/inetpub/wwwroot/a2jdat-20201118/a2jdat/node_modules/can-stache/expressions/call.js:110:16)
3|CALI A2JDAT  |     at Observation.onBound (file:C:/inetpub/wwwroot/a2jdat-20201118/a2jdat/node_modules/can-observation/can-observation.js:87:27)
```

Investigating

**Comment by tobiasnteireho** [comment]
this may be due to low memory. Windows after update seems to be using far more resources. Resizing box to 8GB from 4gb makes it go away. It only appears on a2jlhi test machine, not on any others.

**Comment by tobiasnteireho** [comment]
can no longer reproduce after upping memory
